######################################################################
##
## Filename: top_vga_tb.udo
## Created on: Mon Sep 09 22:57:22 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
