######################################################################
##
## Filename: top_core_tb.udo
## Created on: Tue Jun 11 11:09:41 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
