######################################################################
##
## Filename: top_core.udo
## Created on: Sun Jun 30 23:24:56 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
