######################################################################
##
## Filename: alu_tb.udo
## Created on: Mon Jul 01 20:28:46 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
