`define RAM_ROW_BIT 5//(10 - `PIXEL_ROW_BIT)
`define RAM_COL_BIT 7//(11 - `PIXEL_COL_BIT)
`define PIXEL_ROW_BIT (10 - `RAM_ROW_BIT)//5
`define PIXEL_COL_BIT (11 - `RAM_COL_BIT)//4
`define RAM_ADDR  (21 - `PIXEL_COL_BIT - `PIXEL_ROW_BIT)
`define CHAR_REG_BIT 512//((2**`PIXEL_ROW_BIT)*(2**`PIXEL_COL_BIT)
`define RAM_COL_NUM 80//(1280 / (2**`PIXEL_COL_BIT))
`define RAM_ROW_NUM 32
`define FONT_BIT (8 + `PIXEL_ROW_BIT + `PIXEL_COL_BIT)
