######################################################################
##
## Filename: top_itype_tb.udo
## Created on: Sat May 04 19:22:41 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
