//ascii_code
parameter ascii_1 = 8'h31;
parameter ascii_2 = 8'h32;
parameter ascii_3 = 8'h33;
parameter ascii_4 = 8'h34;
parameter ascii_5 = 8'h35;
parameter ascii_6 = 8'h36;
parameter ascii_7 = 8'h37;
parameter ascii_8 = 8'h38;
parameter ascii_9 = 8'h39;
parameter ascii_0 = 8'h30;
parameter ascii_a = 8'h61;
parameter ascii_b = 8'h62;
parameter ascii_c = 8'h63;
parameter ascii_d = 8'h64;
parameter ascii_e = 8'h65;
parameter ascii_f = 8'h66;
parameter ascii_g = 8'h67;
parameter ascii_h = 8'h68;
parameter ascii_i = 8'h69;
parameter ascii_j = 8'h6a;
parameter ascii_k = 8'h6b;
parameter ascii_l = 8'h6c;
parameter ascii_m = 8'h6d;
parameter ascii_n = 8'h6e;
parameter ascii_o = 8'h6f;
parameter ascii_p = 8'h70;
parameter ascii_q = 8'h71;
parameter ascii_r = 8'h72;
parameter ascii_s = 8'h73;
parameter ascii_t = 8'h74;
parameter ascii_u = 8'h75;
parameter ascii_v = 8'h76;
parameter ascii_w = 8'h77;
parameter ascii_x = 8'h78;
parameter ascii_y = 8'h79;
parameter ascii_z = 8'h7a;
parameter ascii_wave = 8'h60; //`和~
parameter ascii_sub = 8'h2d; //_和-
parameter ascii_add = 8'h3d; //=和+
parameter ascii_left_bracket = 8'h5b; //[和{
parameter ascii_right_bracket = 8'h5d; //]和}
parameter ascii_or = 8'h5c; //\和|
parameter ascii_colon = 8'h3b; //;和：
parameter ascii_quotes = 8'h27; //'和"
parameter ascii_comma = 8'h2c; //,和<
parameter ascii_dot = 8'h2e; //.和>
parameter ascii_div = 8'h2f; ///和?
//shift ascii code
parameter ascii_shift_1 = 8'h21;
parameter ascii_shift_2 = 8'h40;
parameter ascii_shift_3 = 8'h23;
parameter ascii_shift_4 = 8'h24;
parameter ascii_shift_5 = 8'h25;
parameter ascii_shift_6 = 8'h5e;
parameter ascii_shift_7 = 8'h26;
parameter ascii_shift_8 = 8'h2a;
parameter ascii_shift_9 = 8'h28;
parameter ascii_shift_0 = 8'h29;
parameter ascii_shift_wave = 8'h7e; //`和~
parameter ascii_shift_sub = 8'h5f; //_和-
parameter ascii_shift_add = 8'h2b; //=和+
parameter ascii_shift_left_bracket = 8'h7b; //[和{
parameter ascii_shift_right_bracket = 8'h7d; //]和}
parameter ascii_shift_or = 8'h7c; //\和|
parameter ascii_shift_colon = 8'h3a; //;和：
parameter ascii_shift_quotes = 8'h22; //'和"
parameter ascii_shift_comma = 8'h3c; //,和<
parameter ascii_shift_dot = 8'h3e; //.和>
parameter ascii_shift_div = 8'h3f; ///和?

//key_code
parameter kb_1 = 8'h16;
parameter kb_2 = 8'h1e;
parameter kb_3 = 8'h26;
parameter kb_4 = 8'h25;
parameter kb_5 = 8'h2e;
parameter kb_6 = 8'h36;
parameter kb_7 = 8'h3d;
parameter kb_8 = 8'h3e;
parameter kb_9 = 8'h46;
parameter kb_0 = 8'h45;
parameter kb_a = 8'h1c;
parameter kb_b = 8'h32; 
parameter kb_c = 8'h21;
parameter kb_d = 8'h23;
parameter kb_e = 8'h24; 
parameter kb_f = 8'h2b;
parameter kb_g = 8'h34;
parameter kb_h = 8'h33;
parameter kb_i = 8'h43;
parameter kb_j = 8'h3b;
parameter kb_k = 8'h42;
parameter kb_l = 8'h4b;
parameter kb_m = 8'h3a;
parameter kb_n = 8'h31;
parameter kb_o = 8'h44;
parameter kb_p = 8'h4d;
parameter kb_q = 8'h15;
parameter kb_r = 8'h2d;
parameter kb_s = 8'h1b;
parameter kb_t = 8'h2c;
parameter kb_u = 8'h3c;
parameter kb_v = 8'h2a;
parameter kb_w = 8'h1d;
parameter kb_x = 8'h22;
parameter kb_y = 8'h35;
parameter kb_z = 8'h1a;
parameter kb_wave = 8'h0e; //`和~
parameter kb_sub = 8'h4e; //_和-
parameter kb_add = 8'h55; //=和+
parameter kb_left_bracket = 8'h54; //[和{
parameter kb_right_bracket = 8'h5b; //]和}
parameter kb_or = 8'h5d; //\和|
parameter kb_colon = 8'h4c; //;和：
parameter kb_quotes = 8'h52; //'和"
parameter kb_comma = 8'h41; //,和<
parameter kb_dot = 8'h49; //.和>
parameter kb_div = 8'h4a; ///和?
//功能键
parameter kb_ESC = 8'h76;
parameter kb_F1 = 8'h05;
parameter kb_F2 = 8'h06;
parameter kb_F3 = 8'h04;
parameter kb_F4 = 8'h0c;
parameter kb_F5 = 8'h03;
parameter kb_F6 = 8'h0b;
parameter kb_F7 = 8'h83;
parameter kb_F8 = 8'h0a;
parameter kb_F9 = 8'h01;
parameter kb_F10 = 8'h09;
parameter kb_F11 = 8'h78;
parameter kb_F12 = 8'h07;
parameter kb_TAB = 8'h0d;
parameter kb_CAPS = 8'h58;
parameter kb_SHIFT_LEFT = 8'h12;
parameter kb_SHIFT_RIGHT = 8'h59;
parameter kb_CTRL = 8'h14; //左边的ctrl是14，右边的alt是E0 14
parameter kb_ALT = 8'h11; //左边的alt是11，右边的alt是E0 11
parameter kb_SPACE = 8'h29;
parameter kb_ENTER = 8'h5A;
parameter kb_BACK = 8'h66;
//扩展键（键码E0开头）
parameter kb_UP =	8'h75;
parameter kb_DOWN = 8'h72;
parameter kb_LEFT = 8'h6b;
parameter kb_RIGHT = 8'h74;