######################################################################
##
## Filename: file_write_tb.udo
## Created on: Sun Aug 18 13:49:33 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
