######################################################################
##
## Filename: ram.udo
## Created on: Tue Sep 17 23:10:26 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
