######################################################################
##
## Filename: state_machine_tb.udo
## Created on: Wed May 22 18:10:27 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
