######################################################################
##
## Filename: top_itype_tb.udo
## Created on: Thu May 09 21:12:03 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
