######################################################################
##
## Filename: clkdiv_init_tb.udo
## Created on: Mon Jul 08 16:21:58 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
